spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8888

app:
  jwtSecret: c4d68758a5aa67a7d39f1588a6c3f89a145f6e25a1e862ebd94a517a7a129ad5
  jwtExpirationMs: 86400000
  jwtRefreshExpirationMs: 86400000
  emailServiceURI: http://localhost:8070/api/v1/email