eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          predicates:
            - Path=/api/v1/auth/**
          uri: http://localhost:8090
        - id: email-service
          predicates:
            - Path=/api/v1/email/**
          uri: http://localhost:8070